// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package data

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2929cd5bDecodeGithubComWavesplatformGowavesCmdWmdInternalData(in *jlexer.Lexer, out *CandlesInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(CandlesInfo, 0, 0)
			} else {
				*out = CandlesInfo{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 CandleInfo
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2929cd5bEncodeGithubComWavesplatformGowavesCmdWmdInternalData(out *jwriter.Writer, in CandlesInfo) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v CandlesInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2929cd5bEncodeGithubComWavesplatformGowavesCmdWmdInternalData(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CandlesInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2929cd5bEncodeGithubComWavesplatformGowavesCmdWmdInternalData(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CandlesInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2929cd5bDecodeGithubComWavesplatformGowavesCmdWmdInternalData(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CandlesInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2929cd5bDecodeGithubComWavesplatformGowavesCmdWmdInternalData(l, v)
}
func easyjson2929cd5bDecodeGithubComWavesplatformGowavesCmdWmdInternalData1(in *jlexer.Lexer, out *CandleInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "timestamp":
			out.Timestamp = uint64(in.Uint64())
		case "open":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Open).UnmarshalJSON(data))
			}
		case "high":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.High).UnmarshalJSON(data))
			}
		case "low":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Low).UnmarshalJSON(data))
			}
		case "close":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Close).UnmarshalJSON(data))
			}
		case "vwap":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Average).UnmarshalJSON(data))
			}
		case "volume":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Volume).UnmarshalJSON(data))
			}
		case "priceVolume":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PriceVolume).UnmarshalJSON(data))
			}
		case "confirmed":
			out.Confirmed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2929cd5bEncodeGithubComWavesplatformGowavesCmdWmdInternalData1(out *jwriter.Writer, in CandleInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Timestamp))
	}
	{
		const prefix string = ",\"open\":"
		out.RawString(prefix)
		out.Raw((in.Open).MarshalJSON())
	}
	{
		const prefix string = ",\"high\":"
		out.RawString(prefix)
		out.Raw((in.High).MarshalJSON())
	}
	{
		const prefix string = ",\"low\":"
		out.RawString(prefix)
		out.Raw((in.Low).MarshalJSON())
	}
	{
		const prefix string = ",\"close\":"
		out.RawString(prefix)
		out.Raw((in.Close).MarshalJSON())
	}
	{
		const prefix string = ",\"vwap\":"
		out.RawString(prefix)
		out.Raw((in.Average).MarshalJSON())
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"priceVolume\":"
		out.RawString(prefix)
		out.Raw((in.PriceVolume).MarshalJSON())
	}
	{
		const prefix string = ",\"confirmed\":"
		out.RawString(prefix)
		out.Bool(bool(in.Confirmed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CandleInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2929cd5bEncodeGithubComWavesplatformGowavesCmdWmdInternalData1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CandleInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2929cd5bEncodeGithubComWavesplatformGowavesCmdWmdInternalData1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CandleInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2929cd5bDecodeGithubComWavesplatformGowavesCmdWmdInternalData1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CandleInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2929cd5bDecodeGithubComWavesplatformGowavesCmdWmdInternalData1(l, v)
}
