// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package data

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson727fe99aDecodeGithubComWavesplatformGowavesCmdWmdInternalData(in *jlexer.Lexer, out *WMDStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "current_height":
			out.CurrentHeight = int(in.Int())
		case "last_block_id":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastBlockID).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson727fe99aEncodeGithubComWavesplatformGowavesCmdWmdInternalData(out *jwriter.Writer, in WMDStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"current_height\":"
		out.RawString(prefix[1:])
		out.Int(int(in.CurrentHeight))
	}
	{
		const prefix string = ",\"last_block_id\":"
		out.RawString(prefix)
		out.Raw((in.LastBlockID).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WMDStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson727fe99aEncodeGithubComWavesplatformGowavesCmdWmdInternalData(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WMDStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson727fe99aEncodeGithubComWavesplatformGowavesCmdWmdInternalData(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WMDStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson727fe99aDecodeGithubComWavesplatformGowavesCmdWmdInternalData(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WMDStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson727fe99aDecodeGithubComWavesplatformGowavesCmdWmdInternalData(l, v)
}
