// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package data

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA050b59dDecodeGithubComWavesplatformGowavesCmdWmdInternalData(in *jlexer.Lexer, out *Substitutions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Substitutions, 0, 1)
			} else {
				*out = Substitutions{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Substitution
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA050b59dEncodeGithubComWavesplatformGowavesCmdWmdInternalData(out *jwriter.Writer, in Substitutions) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Substitutions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA050b59dEncodeGithubComWavesplatformGowavesCmdWmdInternalData(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Substitutions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA050b59dEncodeGithubComWavesplatformGowavesCmdWmdInternalData(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Substitutions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA050b59dDecodeGithubComWavesplatformGowavesCmdWmdInternalData(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Substitutions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA050b59dDecodeGithubComWavesplatformGowavesCmdWmdInternalData(l, v)
}
func easyjsonA050b59dDecodeGithubComWavesplatformGowavesCmdWmdInternalData1(in *jlexer.Lexer, out *Substitution) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "assetID":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.AssetID[:], in.Bytes())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA050b59dEncodeGithubComWavesplatformGowavesCmdWmdInternalData1(out *jwriter.Writer, in Substitution) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"assetID\":"
		out.RawString(prefix)
		out.Raw((in.AssetID).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Substitution) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA050b59dEncodeGithubComWavesplatformGowavesCmdWmdInternalData1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Substitution) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA050b59dEncodeGithubComWavesplatformGowavesCmdWmdInternalData1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Substitution) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA050b59dDecodeGithubComWavesplatformGowavesCmdWmdInternalData1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Substitution) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA050b59dDecodeGithubComWavesplatformGowavesCmdWmdInternalData1(l, v)
}
